# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version of Driver to the Google Play"
  lane :deployDriver do
    gradle(
        task: "clean bundle",
        flavor: "Driver",
        build_type: "Release",
        properties: {
          "android.injected.signing.store.file" => "$PWD/app/keystore.jks",
          "android.injected.signing.store.password" => ENV['RELEASE_STORE_PASSWORD'],
          "android.injected.signing.key.alias" => ENV['RELEASE_KEY_ALIAS'],
          "android.injected.signing.key.password" => ENV['RELEASE_KEY_PASSWORD'],
        })
    upload_to_play_store(
        aab: "app/build/outputs/bundle/driverRelease/app-driver-release.aab",
        json_key: "google-play-key.json",
        package_name: "h_mal.appttude.com.driver")
  end

  desc "Deploy a new version of Admin to the Google Play"
  lane :deployAdmin do
    gradle(task: "clean bundle", flavor: "Admin", build_type: "Release")
    upload_to_play_store(aab: "app/build/outputs/bundle/adminRelease/app-admin-release.aab", json_key: "google-play-key.json", package_name: "h_mal.appttude.com.driver.admin")
  end
end
